import { describe, it, expect, beforeEach } from 'vitest'
import { SupabaseCrmStore } from '@/lib/data/supabase'
import { comoServico, limparBanco } from './helpers/db'
import { clienteDoUsuario } from './helpers/cliente'
import { montarCenario, etapa, criarLead, type Cenario } from './helpers/cenario'

describe('0006 — desempate de ordenacao de lead_events', () => {
  let c: Cenario
  beforeEach(async () => {
    await limparBanco()
    c = await montarCenario()
  })

  it('devolve o mais recente primeiro quando criado_em empata', async () => {
    const leadId = await criarLead(c, 'Empate', c.adminId, etapa(c, 'Novo lead'))

    // Os tres eventos nascem na MESMA transacao, entao now() e identico nos
    // tres: e exatamente o cenario que o Plano 4 cria ao ingerir um lead.
    await comoServico((cli) =>
      cli.query(
        `insert into public.lead_events (lead_id, tipo, payload, ator_id)
         values ($1, 'primeiro', '{}'::jsonb, $2),
                ($1, 'segundo',  '{}'::jsonb, $2),
                ($1, 'terceiro', '{}'::jsonb, $2)`,
        [leadId, c.adminId],
      ),
    )

    const mesmoInstante = await comoServico(async (cli) => {
      const r = await cli.query<{ distintos: string }>(
        'select count(distinct criado_em) as distintos from public.lead_events where lead_id = $1',
        [leadId],
      )
      return r.rows[0].distintos
    })
    // Se este assert falhar, o cenario nao esta testando o que promete.
    expect(mesmoInstante).toBe('1')

    const cliente = await clienteDoUsuario(c.adminId)
    const store = new SupabaseCrmStore(cliente, c.accountId, c.adminId)

    const r = await store.eventosDoLead(leadId)
    if (!r.ok) throw new Error(r.erro)
    expect(r.valor.map((e) => e.tipo)).toEqual(['terceiro', 'segundo', 'primeiro'])
  })

  it('seq e monotonica e crescente na ordem de insercao', async () => {
    const leadId = await criarLead(c, 'Sequencia', c.adminId, etapa(c, 'Novo lead'))
    await comoServico(async (cli) => {
      await cli.query(
        `insert into public.lead_events (lead_id, tipo, ator_id) values ($1, 'a', $2)`,
        [leadId, c.adminId],
      )
      await cli.query(
        `insert into public.lead_events (lead_id, tipo, ator_id) values ($1, 'b', $2)`,
        [leadId, c.adminId],
      )
    })

    const seqs = await comoServico(async (cli) => {
      const r = await cli.query<{ tipo: string; seq: string }>(
        'select tipo, seq from public.lead_events where lead_id = $1 order by seq',
        [leadId],
      )
      return r.rows
    })
    expect(seqs.map((s) => s.tipo)).toEqual(['a', 'b'])
    expect(Number(seqs[1].seq)).toBeGreaterThan(Number(seqs[0].seq))
  })

  it('nao deixa a aplicacao escrever seq', async () => {
    const leadId = await criarLead(c, 'Imutavel', c.adminId, etapa(c, 'Novo lead'))
    // O texto "generated always" so aparece no DETAIL do erro do Postgres, nao
    // na .message que o node-postgres usa para o Error lancado — verificado
    // contra a instancia local (codigo 428C9). "non-DEFAULT value" na message
    // ja prova o ponto: uma coluna GENERATED BY DEFAULT aceitaria o insert
    // explicito em silencio; so GENERATED ALWAYS rejeita assim.
    await expect(
      comoServico((cli) =>
        cli.query(
          `insert into public.lead_events (lead_id, tipo, ator_id, seq)
           values ($1, 'forcado', $2, 99)`,
          [leadId, c.adminId],
        ),
      ),
    ).rejects.toThrow(/cannot insert a non-default value/i)
  })
})
